# Generated by Django 2.2.16 on 2022-02-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220218_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-name']},
        ),
    ]
